### PR TITLE
Fix passing form props to nested children. Add `isFormField` option.

### LINKED ISSUE #40: Nested inputs in form do not get initial data
the field named email does not get initialData, but the fields like first_name do
```
<Form {...formProps}>
            <InputText name='first_name' label='First Name' placeholder='first name' />
            <InputText disabled name='last_name' label='Last Name' placeholder={'last name'} />
            <TextArea name='bio' label='Bio' />
            <div className='input-hint'>Limited to 200 characters</div>

            <fieldset>
              <legend>Email</legend>
              <InputText name='email' label='Email Address' placeholder='email' type='email' />
            </fieldset>

            <fieldset>
              <legend>Password</legend>
              <InputText name='password' label='Enter New Password' placeholder='••••••••' type='password' />
              <InputText name='passwordConfirm' label='Confirm New Password' placeholder='••••••••' type='password' />
            </fieldset>

            <fieldset>
              <legend>Notifications</legend>
              <LightSwitch name='push_notifications' text='I want to receive push notifications' />
              <LightSwitch name='email_notifications' text='I want to receive email notifications' />
            </fieldset>
            <button type='submit'>Login</button>
</Form>
```

### PR DESCRIPTION
**Pull request by adriaanwm**
fixes #40 and adds option for any child of form to accept form props with attribute `isFormField`.

### CODE REVIEW

File: components/form/form.js [hunk 1]
```diff
@@ -46,12 +46,12 @@ const getNodeName = child =>
...
 
-// Is one of the above defined form fields, and has a `name`
-// prop set. We can't sync state if the component doesn't have
+// Is one of the above defined form fields, (or has attribute isFormField)
+// and has a `name` prop set. We can't sync state if the component doesn't have
 // have a `name` prop set.
 const isFormField = child => {
   const name = getNodeName(child)
-  if (!formFieldNames.includes(name)) {
+  if (!formFieldNames.includes(name) && !(child.attributes && child.attributes.isFormField)) {
```
Comment (staydecent) [inline components/form/form.js]: should use getProps for React/Preact compat.

**Review by staydecent — CHANGES_REQUESTED** [review]
This is amazing. Apparently I don't nest form fields in my apps....

Just 1 small change for Preact/React compat.

**Review by staydecent — APPROVED** [review]
